---
# defaults file for docker roles
docker_repo_url: "https://download.docker.com/linux/ubuntu"
docker_gpg_url: "{{ docker_repo_url }}/gpg"
docker_keyring_path: "/etc/apt/keyrings"
docker_keyring_file: "{{ docker_keyring_path }}/docker.asc"
docker_sources_file: "/etc/apt/sources.list.d/docker.sources"

docker_prereq_packages:
  - ca-certificates
  - curl

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin